package com.tpi_pais.mega_store.utils;

import lombok.Data;
import org.springframework.context.annotation.Bean;

/**
 * Clase EmailCodigoValidacion
 * Representa la estructura de un correo electronico con un codigo de validacion.
 */

public class EmailCodigoValidacion {

    public static final String logoUrl = "https://i.ibb.co/NLytV57/logo.png";
    public static final String emailHtmlTemplate = "<!DOCTYPE html><html><head><meta charset=\"UTF-8\"><style>body {font-family: Arial, sans-serif;color: #ffffff;margin: 0;padding: 0;background-color: #c99af3;}.container {width: 100%;max-width: 600px;margin: 0 auto;padding: 20px;background-color: #c99af3;}.header {text-align: center;background-color: #c99af3;padding: 10px;border: 4px solid white;border-radius: 15px 15px 0px 0px;}h1 {margin-top: 0px;}.content {background-color: #ffffff;padding: 30px;text-align: center;color: #6b2ba3;border-radius: 0px 0px 15px 15px;}.footer {text-align: center;font-size: 12px;color: #f0e6ff;padding-top: 20px;}.button {display: inline-block;background-color: #b071e4;color: white;padding: 10px 20px;text-decoration: none;border-radius: 5px;font-weight: bold;}.code {font-size: 24px;color: #b071e4;margin: 20px 0;}.logo {width: 100px;height: auto;margin-bottom: 20px;}</style></head><body><div class=\"container\"><div class=\"header\"><img src=\"https://i.ibb.co/NLytV57/logo.png\" alt=\"Mega Store Logo\" class=\"logo\" /><h1>Bienvenido a Mega Store</h1></div><div class=\"content\"><h2 class=\"code\">¡Hola, y bienvenido!</h2><p>Gracias por unirte a Mega Store. Para completar el proceso de registro, por favor verifica tu dirección de correo electrónico usando el código a continuación:</p><div class=\"code\">{CODIGO_VERIFICACION}</div><p>Introduce este código en la página de verificación para activar tu cuenta.</p></div><div class=\"footer\"><p>Si no realizaste esta solicitud, puedes ignorar este correo.</p><p>&copy; 2024 Mega Store. Todos los derechos reservados.</p></div></div></body></html>";
    public static final String passwordResetEmailTemplate = "<!DOCTYPE html><html><head><meta charset=\"UTF-8\"><style>body {font-family: Arial, sans-serif;color: #ffffff;margin: 0;padding: 0;background-color: #c99af3;}.container {width: 100%;max-width: 600px;margin: 0 auto;padding: 20px;background-color: #c99af3;}.header {text-align: center;background-color: #c99af3;padding: 10px;border: 4px solid white;border-radius: 15px 15px 0px 0px;}h1 {margin-top: 0px;}.content {background-color: #ffffff;padding: 30px;text-align: center;color: #6b2ba3;border-radius: 0px 0px 15px 15px;}.footer {text-align: center;font-size: 12px;color: #f0e6ff;padding-top: 20px;}.button {display: inline-block;background-color: #b071e4;color: white;padding: 10px 20px;text-decoration: none;border-radius: 5px;font-weight: bold;}.code {font-size: 24px;color: #b071e4;margin: 20px 0;}.logo {width: 100px;height: auto;margin-bottom: 20px;}</style></head><body><div class=\"container\"><div class=\"header\"><img src=\"https://i.ibb.co/NLytV57/logo.png\" alt=\"Mega Store Logo\" class=\"logo\" /><h1>Recuperación de Contraseña</h1></div><div class=\"content\"><h2 class=\"code\">¿Olvidaste tu contraseña?</h2><p>Hemos recibido una solicitud para restablecer la contraseña de tu cuenta en Mega Store. Usa el siguiente código para continuar con el proceso:</p><div class=\"code\">{CODIGO_RECUPERACION}</div><p>Si no solicitaste un restablecimiento de contraseña, puedes ignorar este correo y tu contraseña permanecerá sin cambios.</p></div><div class=\"footer\"><p>&copy; 2024 Mega Store. Todos los derechos reservados.</p></div></div></body></html>";
    public static final String stockCriticalAlertEmailTemplate = "<!DOCTYPE html><html><head><meta charset=\"UTF-8\"><style>body {font-family: Arial, sans-serif; margin: 0; padding: 0; background-color: #ffe5e5;}.container {width: 100%; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #ffe5e5;}.header {text-align: center; background-color: #d32f2f; padding: 10px; border: 4px solid white; border-radius: 15px 15px 0px 0px; color: white;}h1 {margin-top: 0px;}.content {background-color: #ffffff; padding: 30px; text-align: center; color: #d32f2f; border-radius: 0px 0px 15px 15px;}.footer {text-align: center; font-size: 12px; color: #b71c1c; padding-top: 20px;}.alert-text {font-size: 18px; font-weight: bold; color: #d32f2f;}.code {font-size: 24px; color: #b71c1c; margin: 20px 0; font-weight: bold;}</style></head><body><div class=\"container\"><div class=\"header\"><h1>⚠️ ALERTA CRÍTICA ⚠️</h1></div><div class=\"content\"><h2 class=\"alert-text\">¡Stock Críticamente Bajo!</h2><p>El producto <strong>{NOMBRE_PRODUCTO}</strong> ha bajado por debajo del stock mínimo.</p><div class=\"code\">Stock Actual: {STOCK_ACTUAL}</div><p>Por favor, reabastece este producto lo antes posible.</p></div><div class=\"footer\"><p>&copy; 2024 Mega Store. Todos los derechos reservados.</p></div></div></body></html>";
    public static final String stockModerateAlertEmailTemplate = "<!DOCTYPE html><html><head><meta charset=\"UTF-8\"><style>body {font-family: Arial, sans-serif; margin: 0; padding: 0; background-color: #fff5e1;}.container {width: 100%; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #fff5e1;}.header {text-align: center; background-color: #ff9800; padding: 10px; border: 4px solid white; border-radius: 15px 15px 0px 0px; color: white;}h1 {margin-top: 0px;}.content {background-color: #ffffff; padding: 30px; text-align: center; color: #ff9800; border-radius: 0px 0px 15px 15px;}.footer {text-align: center; font-size: 12px; color: #f57c00; padding-top: 20px;}.alert-text {font-size: 18px; font-weight: bold; color: #ff9800;}.code {font-size: 24px; color: #f57c00; margin: 20px 0; font-weight: bold;}</style></head><body><div class=\"container\"><div class=\"header\"><h1>⚠️ ALERTA DE STOCK ⚠️</h1></div><div class=\"content\"><h2 class=\"alert-text\">¡Stock en Nivel Bajo!</h2><p>El producto <strong>{NOMBRE_PRODUCTO}</strong> está entre el stock mínimo y medio.</p><div class=\"code\">Stock Actual: {STOCK_ACTUAL}</div><p>Revisa la demanda y planifica un posible reabastecimiento.</p></div><div class=\"footer\"><p>&copy; 2024 Mega Store. Todos los derechos reservados.</p></div></div></body></html>";
}
